# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 2
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Tzeaca Computers/Desktop/lab ac/lab6ID pipeline/lab6ID.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Tzeaca Computers/Desktop/lab ac/lab6ID pipeline/lab6ID.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo {c:/Users/Tzeaca Computers/Desktop/lab ac/lab6ID pipeline/lab6ID.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {C:/Users/Tzeaca Computers/Desktop/lab ac/lab6ID pipeline/lab6ID.srcs/sources_1/new/EX.vhd}
  {C:/Users/Tzeaca Computers/Desktop/lab ac/lab6ID pipeline/lab6ID.srcs/sources_1/new/ID.vhd}
  {C:/Users/Tzeaca Computers/Desktop/lab ac/lab6ID pipeline/lab6ID.srcs/sources_1/new/IF.vhd}
  {C:/Users/Tzeaca Computers/Desktop/lab ac/lab6ID pipeline/lab6ID.srcs/sources_1/new/MEM.vhd}
  {C:/Users/Tzeaca Computers/Desktop/lab ac/lab6ID pipeline/lab6ID.srcs/sources_1/new/MPG.vhd}
  {C:/Users/Tzeaca Computers/Desktop/lab ac/lab6ID pipeline/lab6ID.srcs/sources_1/new/SSD.vhd}
  {C:/Users/Tzeaca Computers/Desktop/lab ac/lab6ID pipeline/lab6ID.srcs/sources_1/new/UC.vhd}
  {C:/Users/Tzeaca Computers/Desktop/lab ac/lab6ID pipeline/lab6ID.srcs/sources_1/new/test_new.vhd}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/Tzeaca Computers/Desktop/lab ac/Basys3_test_env.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Tzeaca Computers/Desktop/lab ac/Basys3_test_env.xdc}}]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top test_new -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef test_new.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file test_new_utilization_synth.rpt -pb test_new_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
